name = "ThinModules"
uuid = "9d3818cf-6167-4773-80a0-959b9e922fa8"
authors = ["Haoran SUN <hrsun@zju.edu.cn> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
